<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
    <joint name="camera_joint" type='fixed'>
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${chassis_radius} 0 ${chassis_thick+(chassis_thick/2.5)}" rpy="0 0 0" />
    </joint>
    <link name="camera_link">
        <visual>
            <geometry>
            <!-- ${wheel_width/2} ${wheel_radius} ${wheel_radius} -->
                <box size="${cam_height} ${cam_width} ${cam_length}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <!-- Camera sticks out, could easily get hit -->
        <collision>
            <origin xyz="0 0 ${wheel_z}" rpy="0 ${ninety_deg} 0"/>
            <geometry>
                <box size="${cam_height} ${cam_width} ${cam_length}"/>
            </geometry>
        </collision>
        <!-- Camera IS on a fixed joint, no need for inertia -->
        <!-- <xacro:inertial_box mass="0.01"
                                x="${cam_height}"
                                y="${cam_width}"
                                z="${cam_length}">
            <origin xyz="0 0 ${wheel_z}" rpy="0 ${ninety_deg} 0"/>
        </xacro:inertial_box> -->
    </link>

    <joint name="camera_optical_joint" type='fixed'>
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    </joint>

    <link name="camera_link_optical"></link>

    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        
        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>0.94</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <!-- As close as 50mm, or 0.05 -->
                    <near>0.05</near>
                    <!-- As far as 8m, or 8.0 -->
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>


</robot>