<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
    <joint name="laser_joint" type='fixed'>
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="${chassis_radius} 0 ${chassis_thick+(chassis_thick/2.5)}" rpy="0 0 0" />
    </joint>
    <link name="laser_frame">
        <visual>
            <geometry>
            <!-- ${wheel_width/2} ${wheel_radius} ${wheel_radius} -->
                <box size="${cam_height} ${cam_width} ${cam_length}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${wheel_z}" rpy="0 ${ninety_deg} 0"/>
            <geometry>
                <box size="${cam_height} ${cam_width} ${cam_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.01"
                                x="${cam_height}"
                                y="${cam_width}"
                                z="${cam_length}">
            <origin xyz="0 0 ${wheel_z}" rpy="0 ${ninety_deg} 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>
        
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <!-- -180 to +180 in radians -->
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <!-- 300millimeters -->
                    <min>0.3</min>
                    <!-- 12m -->
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>


</robot>